create table if not exists public.paper_notification_outbox (
    notification_id bigint generated by default as identity primary key,
    event_key text not null unique,
    strategy_id text not null,
    position_id bigint not null,
    notification_type text not null check (notification_type in ('ENTRY', 'EXIT')),
    payload jsonb not null,
    status text not null default 'PENDING'
        check (status in ('PENDING', 'PROCESSING', 'SENT', 'FAILED')),
    attempt_count integer not null default 0,
    next_attempt_at timestamptz not null default now(),
    provider_message_id text,
    last_error text,
    created_at timestamptz not null default now(),
    sent_at timestamptz,
    updated_at timestamptz not null default now()
);

create index if not exists paper_notification_pending_idx
    on public.paper_notification_outbox (status, next_attempt_at, created_at);

alter table public.paper_notification_outbox enable row level security;

revoke all on public.paper_notification_outbox from anon, authenticated;
grant select, insert, update on public.paper_notification_outbox to service_role;
grant usage, select on sequence public.paper_notification_outbox_notification_id_seq
    to service_role;

create or replace function public.enqueue_paper_position_notification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    next_type text;
begin
    if tg_op = 'INSERT' and new.status = 'OPEN' then
        next_type := 'ENTRY';
    elsif tg_op = 'UPDATE'
        and old.status is distinct from new.status
        and new.status = 'OPEN' then
        next_type := 'ENTRY';
    elsif tg_op = 'UPDATE'
        and old.status = 'OPEN'
        and new.status = 'CLOSED' then
        next_type := 'EXIT';
    else
        return new;
    end if;

    insert into public.paper_notification_outbox (
        event_key,
        strategy_id,
        position_id,
        notification_type,
        payload
    ) values (
        new.strategy_id || ':' || new.position_id::text || ':' || next_type,
        new.strategy_id,
        new.position_id,
        next_type,
        new.payload
    ) on conflict (event_key) do nothing;

    return new;
end;
$$;

drop trigger if exists paper_position_notification_trigger
    on public.paper_live_positions;
create trigger paper_position_notification_trigger
after insert or update of status on public.paper_live_positions
for each row execute function public.enqueue_paper_position_notification();

comment on table public.paper_notification_outbox is
    'Outbox idempoten untuk notifikasi ENTRY dan EXIT paper live trading.';
